nginx/ansible-role-nginx-config

CHANGELOG.md
Update the CHANGELOG to prepare the 0.1 release
=> Prepare 0.1 release

CHANGELOG.md, defaults/main/template.yml, molecule/common/playbooks/default_converge.yml, templates/http/default.conf.j2
Add ip restriction to web servers config.
=> Add IP restriction for web servers

.travis.yml
=> Update Ansible to 2.9.13

meta/main.yml
Update Ansible Galaxy metadata
=> Update Ansible Galaxy metadata

.travis.yml, README.md, molecule/common/playbooks/default_converge.yml
* Update the README to point to the main branch instead of master
* Explicitly set the `yamllint` version in Travis
* Add the rewrite directive to the tests (closes #9)
=> Update README, set yamllint version, add rewrite to tests

CHANGELOG.md, README.md
=> Readme changes

CHANGELOG.md, README.md
Add a survey to the README and improve the README structure by using tables where relevant.
=> Add survey to README

CHANGELOG.md, templates/nginx.conf.j2
Correctly import `app_protect` global directives in template.
=> Fix App Protect template import

CHANGELOG.md, handlers/main.yml, tasks/config/debug-output.yml
Some tasks would incorrectly fail when running the role in check mode. Fixes #32.
=> Fix check mode

CHANGELOG.md, defaults/main/template.yml, molecule/common/playbooks/oss_requirements.yml, molecule/common/playbooks/plus_requirements.yml, molecule/default/converge.yml, molecule/plus/converge.yml, templates/http/api.conf.j2, templates/http/status.conf.j2
ENHANCEMENTS:
*   Improve templating of stub status and REST API config.
BUG FIXES:
*   Fix issue with access log in stub status and REST API config template not being properly parsed.
=> Fix and improve stub status and REST API templating

CHANGELOG.md, defaults/main/template.yml, molecule/default/converge.yml, molecule/plus/converge.yml
sub_filter values in template are rendered using the ternary operator, which should be boolean values instead of "on"/"off" string values
=> Sub filter defaults fix

.github/workflows/molecule.yml, tasks/config/cleanup-config.yml
This is a small change, where I didn't tested Molecule tests and added new ones.
Tested on Ansible 2.9.13 / 2.10.4, Python 3.9.0 / 3.9.1, MacOS Catalina (10.15.7)
-   [ ] I have added Molecule tests that prove my fix is effective or that my feature works
-   [ ] I have checked that all Molecule tests pass after adding my changes
=> Simplified list of files for cleanup-config.yml

.github/workflows/molecule.yml, CHANGELOG.md, README.md
*   Update Ansible base to `2.10.4`, Ansible to `2.10.5`, Molecule to `3.2.2` and Docker Python SDK to `4.4.1`.
*   Update copyright notice.
=> Update Python packages and update copyright notice

.github/workflows/galaxy.yml, CHANGELOG.md, README.md, defaults/main/template.yml, meta/main.yml, molecule/common/playbooks/oss_requirements.yml, molecule/common/playbooks/plus_requirements.yml, molecule/default/converge.yml, templates/http/default.conf.j2, templates/http/grpc.j2, templates/nginx.conf.j2
*   Add support for NGINX GRPC directives (resolves #3).
*   Only run GitHub actions Galaxy CI/CD workflow when a new release is published.
*   Update list of supported platforms.
=> Add support for NGINX GRPC directives

CHANGELOG.md, defaults/main/template.yml, molecule/default/converge.yml, templates/http/default.conf.j2, templates/http/gzip.j2, templates/nginx.conf.j2
* Add support for NGINX GZIP directives (resolves #42)
* Fix GRPC directives placement within `defaults/main/template.yml`
=> Add support for NGINX GZIP directives

CHANGELOG.md, defaults/main/upload.yml, molecule/common/files/snippets/location_snippet.conf, molecule/stable_push/converge.yml, tasks/config/upload-config.yml
Add support for configuration snippets (resolves #5).
=> Add support for configuration snippets

CHANGELOG.md, templates/http/default.conf.j2, templates/nginx.conf.j2, templates/stream/default.conf.j2
Fixes #43 until a more in depth refactor takes place
=> Tweak inconsistent types

CHANGELOG.md, defaults/main/template.yml, templates/nginx.conf.j2
Add Jinja2 checks to all config template parameters to ensure that they are only included when appropriately defined. Resolves #4.
=> Add Jinja2 checks to all config template parameters

tasks/config/template-config.yml
Removed some redundant forward slashes
-   [X ] I have read the [CONTRIBUTING](https://github.com/nginxinc/ansible-role-nginx-config/blob/main/CONTRIBUTING.md) document
-   [ N/A] I have added Molecule tests that prove my fix is effective or that my feature works
-   [ X] I have checked that all Molecule tests pass after adding my changes
-   [ N/A] I have updated any relevant documentation (`defaults/main/*.yml`, `README.md` and `CHANGELOG.md`)
=> Remove redundant forward slashes

CHANGELOG.md, templates/http/grpc.j2
Fix missing GRPC boolean check in GRPC template. Resolves #94.
=> Fix missing GRPC boolean check in GRPC template

.github/workflows/molecule.yml, .github/workflows/requirements/requirements_ansible.yml, CHANGELOG.md, README.md
Update the Ansible `community.general` collection to `2.5.1` and `community.docker` collection to `1.5.0`. And while at it, remove the temporary GitHub actions step to uninstall the Ansible community distribution (it's no longer an Ansible Lint dependency).
=> Update Ansible collections

CHANGELOG.md, defaults/main/template.yml, molecule/common/requirements/oss_requirements.yml, molecule/common/requirements/plus_requirements.yml, molecule/plus/converge.yml, templates/http/app_protect.j2
Describe the use case and detail of the change. If this PR addresses an issue on GitHub, make sure to include a link to that issue using one of the [supported keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) here in this description (not in the title of the PR).
-   [X] I have read the [CONTRIBUTING](https://github.com/nginxinc/ansible-role-nginx-config/blob/main/CONTRIBUTING.md) document
-   [X] I have added Molecule tests that prove my fix is effective or that my feature works
-   [X] I have checked that all Molecule tests pass after adding my changes
-   [X] I have updated any relevant documentation (`defaults/main/*.yml`, `README.md` and …
=> Add support for NAP 3.2 security log lists

.github/release-drafter.yml, .github/workflows/release-drafter.yml, CHANGELOG.md
First pass at implementing Release Drafter.
=> Implement Release Drafter

.github/release-drafter.yml, CHANGELOG.md, defaults/main/template.yml, molecule/default/converge.yml, templates/http/default.conf.j2, templates/http/ssl.j2
*   Refactor the `ssl` HTTP config template into its own separate file. Almost all variables have changed (check [`defaults/main/template.yml`](https://github.com/nginxinc/ansible-role-nginx-config/blob/main/defaults/main/template.yml) for examples):
*   All `ssl` variables still live within an `ssl` dictionary, but the names have changed to better reflect the official NGINX directive names.
*   `ssl` configs are now supported within both the `http` and `server` contexts.
-   [x] I have checked …
=> Refactor HTTP SSL module

.github/workflows/galaxy.yml, .github/workflows/molecule.yml, .github/workflows/release-drafter.yml, .yamllint, CHANGELOG.md, handlers/main.yml, molecule/cleanup_module/verify.yml, molecule/default/verify.yml, molecule/plus/prepare.yml, molecule/plus/verify.yml, molecule/stable_push/verify.yml, tasks/config/debug-output.yml, tasks/config/template-config.yml, tasks/config/upload-config.yml, tasks/prerequisites/setup-selinux.yml
Replace "yes"/"no" boolean values with "true"/"false" to comply with YAML spec `1.2`.
=> Replace "yes"/"no" boolean values with "true"/"false"

CHANGELOG.md, molecule/common/requirements/oss_requirements.yml, molecule/common/requirements/plus_requirements.yml
Bump the version of the roles required by Molecule to their latest version.
=> Bump the role versions used when testing the role

CHANGELOG.md, defaults/main/template.yml, molecule/common/files/http/server_two.conf, molecule/default/converge.yml, molecule/default/verify.yml, templates/http/default.conf.j2
Includes the alias statement for locations.
Addresses: https://github.com/nginxinc/ansible-role-nginx-config/issues/131
Somehow, i cannot run molecule verify at the moment.
=> Include alias location statement support

CHANGELOG.md, defaults/main/template.yml, molecule/plus/converge.yml, templates/http/default.conf.j2, templates/http/modules.j2
Refactor `server.health_check_plus` into its own dictionary that now includes all the `health_check` module directives.
=> Refactor HTTP health check module

CHANGELOG.md, molecule/common/requirements/plus_requirements.yml, molecule/plus/converge.yml, molecule/plus/molecule.yml, molecule/plus/prepare.yml, templates/http/app_protect_dos.j2, templates/http/app_protect_waf.j2, templates/http/default.conf.j2, templates/nginx.conf.j2
Add support for directives introduced for the NGINX App Protect DoS module. 
Add support for access_log in the location context.
-   [X] I have read the [CONTRIBUTING](https://github.com/nginxinc/ansible-role-nginx-config/blob/main/CONTRIBUTING.md) document
-   [X] I have added Molecule tests that prove my fix is effective or that my feature works
-   [X] I have checked that any relevant Molecule tests pass after adding my changes
-   [X] I have updated any relevant documentation (`defaults/main/*.yml`, `README.md` and `CHANGELOG.md`)
=> Implement support for NAP DoS directives

defaults/main/main.yml
This variable looks as unused. No mention in the codebase and a comment the same as for `nginx_config_debug_output`.
=> Remove unused variable

CHANGELOG.md, defaults/main/template.yml, templates/http/app_protect_waf.j2
Describe the use case and detail of the change. If this PR addresses an issue on GitHub, make sure to include a link to that issue using one of the [supported keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) here in this description (not in the title of the PR).
-   [X] I have read the [CONTRIBUTING](https://github.com/nginxinc/ansible-role-nginx-config/blob/main/CONTRIBUTING.md) document
-   [X] I have checked that any relevant Molecule tests pass after adding my changes
-   [X] I have updated any relevant documentation (`defaults/main/*.yml`, `README.md` and …
=> Add reconnect_period_seconds for NAP 3.5

.github/workflows/molecule.yml, CHANGELOG.md, molecule/plus/molecule.yml
* Update GitHub actions `if` conditionals to use the `contains` function instead of checking for exact names.
* Remove Debian Buster from the `plus` Molecule test since it often fails in the GitHub Actions CI/CD pipeline.
=> Update GitHub Actions

CHANGELOG.md, templates/http/ssl.j2
=> Fix bugged conditional check in the `http/ssl.j2` Jinja2 template

CHANGELOG.md, defaults/main/template.yml, molecule/default/converge.yml, molecule/plus/converge.yml, tasks/config/template-config.yml
Replace `html_file_name` and `html_file_location` with `deployment_location` inside `nginx_config_html_demo_template`.
=> Change HTML template parameters in line with similar parameters

.github/workflows/requirements/requirements_ansible.yml, CHANGELOG.md, README.md, molecule/common/requirements/oss_requirements.yml, molecule/common/requirements/plus_requirements.yml
Bump the Ansible `community.general` collection to `4.4.0` and `community.docker` collection to `2.1.1`.
=> Bump Ansible collections

CHANGELOG.md, defaults/main/selinux.yml, tasks/prerequisites/setup-selinux.yml
Streamline configuring SELinux (and fix a couple typos introduced in #231).
=> Streamline configuring SELinux

.github/workflows/requirements/requirements_ansible.yml, CHANGELOG.md, README.md
Bump `community.docker` collection to `2.3.0`.
=> Bump `community.docker` collection

.github/workflows/requirements/requirements_ansible.yml, CHANGELOG.md, README.md
Bump `community.general` collection to `4.7.0`.
=> Bump `community.general` collection

CHANGELOG.md, defaults/main/template.yml
Improve the NGINX main config defaults to bring them closer to the standard NGINX defaults on a fresh NGINX install.
=> Improve the NGINX main config defaults

.github/workflows/galaxy.yml, .github/workflows/molecule.yml, .github/workflows/release-drafter.yml, CHANGELOG.md, README.md, molecule/cleanup_module/molecule.yml, molecule/common/Dockerfile.j2, molecule/default/molecule.yml, molecule/plus/molecule.yml, molecule/stable_push/molecule.yml
Update GitHub actions to run on Ubuntu 22.04 (and thus support `cgroups` v2).
=> Update GitHub actions to use Ubuntu 22.04

CHANGELOG.md, defaults/main/template.yml, molecule/common/files/snippets/modules.conf, molecule/default/converge.yml, molecule/default/prepare.yml, templates/nginx.conf.j2
Support the `include` directive in the main NGINX context. Resolves #283.
=> Support `include` in the main NGINX context

.github/workflows/requirements/requirements_ansible.yml, .github/workflows/requirements/requirements_ansible_lint.txt, .github/workflows/requirements/requirements_molecule.txt, CHANGELOG.md, README.md
* Temporarily comment out the Ansible compat requirement to let both Ansible Lint and Molecule choose the version of the package they require since they each require a different version.
* Bump Ansible collections.
=> Fine tune Ansible Lint

molecule/default/converge.yml, templates/http/modules.j2
Fixes #362 similar to #358.
The examples already use `enable`.
=> Change http3 attribute check from enabled to enable

CHANGELOG.md, molecule/cleanup_module/converge.yml, molecule/cleanup_module/molecule.yml, molecule/default/converge.yml, molecule/default/molecule.yml, molecule/plus/converge.yml, molecule/plus/molecule.yml, molecule/plus/prepare.yml, molecule/push/converge.yml, molecule/push/molecule.yml
Use local role name in Molecule tests and update the platforms used in the various Molecule scenarios.
=> Use local role name in Molecule tests

CHANGELOG.md, defaults/main/selinux.yml, meta/main.yml, molecule/common/Dockerfile.j2, molecule/common/requirements/oss_requirements.yml, molecule/common/requirements/plus_requirements.yml, molecule/complete_plus/converge.yml, molecule/complete_plus/molecule.yml, molecule/complete_plus/prepare.yml, molecule/complete_plus/verify.yml, tasks/prerequisites/setup-selinux.yml
Remove CentOS 7 related artifacts, tests, and metadata since RHEL 7 related distributions are no longer tested nor supported.
=> chore: Remove CentOS 7 artifacts/tests/metadata

.github/workflows/requirements/requirements_ansible.yml, CHANGELOG.md, README.md
Bump the Ansible `community.general` collection to `9.2.0`, `community.crypto` collection to `2.21.1` and `community.docker` collection to `3.11.0`.
=> feat: Bump Ansible collections

CHANGELOG.md, molecule/api_plus/molecule.yml, molecule/cleanup_config/molecule.yml, molecule/complete/molecule.yml, molecule/default/molecule.yml, molecule/push_config/molecule.yml, molecule/reverse_proxy/molecule.yml, molecule/stub_status/molecule.yml, molecule/web_server/molecule.yml
=> test: Update RHEL UBI images to UBI 9.4

CHANGELOG.md, tasks/validate/validate.yml, vars/main.yml
Add validation tasks to check the Ansible version, the Jinja2 version, and whether the required Ansible collections for this role are installed.
=> feat: Add Ansible/Jinja2/Collections validation

.github/workflows/molecule.yml, .gitignore, CHANGELOG.md, molecule/api_plus/prepare.yml, molecule/common/requirements/oss_requirements.yml, molecule/common/requirements/plus_requirements.yml, molecule/complete_plus/prepare.yml
Update Molecule NGINX Plus tests to work with R33 by introducing the new license JWT.
=> tests: Update version of NGINX Plus in Molecule tests

.github/workflows/milestone-pr.yml
Fix the milestone_pr.yml workflow by replacing the project link.
=> fix: The migrated project has changed number

CHANGELOG.md, defaults/main/template.yml, molecule/complete/converge.yml, molecule/complete_plus/converge.yml, templates/stream/modules.j2
Add templating support for the `ngx_stream_map_module` NGINX module. Closes #385.
=> feat: Template support for the NGINX Stream map module

README.md
=> docs: Fix survey link
