nginx/ansible-role-nginx-config

- CHANGELOG.md
- defaults/main/template.yml
- molecule/common/playbooks/default_converge.yml
- templates/http/default.conf.j2
- templates/nginx.conf.j2
Allow setting `access_log` to "off".
So it will be possible to use this option as before:
```yaml
...
access_log:
- name: main
location: /var/log/nginx/access.log
```
Or set it to `off` or `false` to cancel all access_log directives on the current level:
```yaml
...
access_log: "off"
```
_Copy of …
> Allow setting `access_log` to "off"

- CHANGELOG.md
- defaults/main/main.yml
- tasks/conf/cleanup-config.yml
Ensure that if `nginx_config_cleanup_files` is not defined, the default value will be transformed into a list. Fixes #15. 
-   [ ] I have read the [CONTRIBUTING](https://github.com/nginxinc/ansible-role-nginx-config/blob/master/CONTRIBUTING.md) document
-   [ ] I have added Molecule tests that prove my fix is effective or that my feature works
-   [ ] I have checked that all Molecule tests pass after adding my changes
-   [ ] I have updated any relevant documentation (`defaults/main/*.yml`, `README.md` and `CHANGELOG.md`)
> Fix configs cleanup

- CHANGELOG.md
- README.md
- defaults/main/main.yml
- defaults/main/template.yml
- molecule/common/playbooks/default_converge.yml
- molecule/common/playbooks/module_converge.yml
- molecule/common/playbooks/prepare.yml
- tasks/conf/template-config.yml
- tasks/main.yml
- templates/nginx.conf.j2
Instead of manually setting the modules you want to install to `true` or `false`, you will now have to use either:
*   A newly introduced top level list variable, `nginx_config_modules`.
*   A newly introduced list variable within your main NGINX config template, `nginx_config_main_template.modules`.
This change will simplify adding future supported modules to this role, and allows you to include any external modules you may wish in your NGINX config.
-   [x] I have checked that all Molecule …
> Refactor modules

- .travis.yml
- CHANGELOG.md
- defaults/main/template.yml
- templates/http/status.conf.j2
Fixes #28 by making 8080 the default port for the status page. Moved the status page ACL out of the location block to server to ensure it's applied to all requests. 
-   [x] I have added Molecule tests that prove my fix is effective or that my feature works (Molecule [test](https://github.com/nginxinc/ansible-role-nginx-config/blob/6b7e1e9156c9b1f350a6f68dc2c2a6933faa126b/molecule/default/converge.yml#L60) already used 8080)
-   [x] I have updated any relevant documentation (`defaults/main/*.yml`, `README.md` and …
> Fixes #28: Use port 8080 by default for status page

- CHANGELOG.md
- defaults/main/selinux.yml
- tasks/prerequisites/setup-selinux.yml
Fix issue whereas SELinux state would not be correctly set back to `enforcing` when `nginx_config_selinux: true`. Fixes #46.
> SELinux state should now be correctly set back to `enforcing`

- CHANGELOG.md
- molecule/default/converge.yml
- molecule/plus/converge.yml
- templates/http/default.conf.j2
- templates/stream/default.conf.j2
Added support for `backspin the default templates for http and stream. Parameter as explained by Nginx doc:
```shell
marks the server as a backup server. Connections to the backup server will be passed when the primary servers are unavailable.
```
> Fix #50: Add upstream server backup parameter to templates

- CHANGELOG.md
- templates/http/default.conf.j2
Fix edge case where `proxy_pass` is still required when using `grpc_pass`.
-   [ ] I have added Molecule tests that prove my fix is effective or that my feature works
-   [ ] I have checked that all Molecule tests pass after adding my changes
> Make `proxy_pass` optional

- CHANGELOG.md
- defaults/main/template.yml
- molecule/default/converge.yml
- molecule/plus/converge.yml
- templates/http/default.conf.j2
Rename `proxy_hide_headers` to `proxy_hide_header` to align with NGINX directive names. Closes #51.
> Rename `proxy_hide_headers` to `proxy_hide_header`

- CHANGELOG.md
- molecule/default/converge.yml
- molecule/plus/converge.yml
- templates/http/default.conf.j2
Remove/merge the `web_server` and `reverse_proxy` sub-dictionary keys from the HTTP templates. These often lead to confusing and unnecessary code duplication and hard to maintain code. To update your templates simply remove both keys and adjust your spacing accordingly.
> Remove `web_server` and `reverse_proxy` template dictionary keys

- CHANGELOG.md
- handlers/main.yml
In App Protect environments on SELinux enforced systems, the `nginx -t` handler fails when run from a directory that the nginx process' user does not have access to. Fix: cd to etc nginx before running test command.
-   [X] I have checked that all Molecule tests pass after adding my changes
-   [X] I have updated any relevant documentation (`defaults/main/*.yml`, `README.md` and `CHANGELOG.md`)
> Change directory to `/etc/nginx` before running NGINX config check

- CHANGELOG.md
- defaults/main/template.yml
- molecule/default/converge.yml
- molecule/plus/converge.yml
- templates/http/default.conf.j2
- templates/http/upstream.j2
Refactor the `upstream` HTTP config template into its own separate file. The following variables have changed (check `defaults/main/template.yml` for example values):
*   `port` is no longer supported. Instead, include the port as part of your `address`.
*   `lb_method` is no longer supported. Instead, you will have to specifically set the method you want to use.
*   `zone_name` and `zone_size` have been modified into a dictionary.
*   `sticky_cookie` is no longer supported as is. You will now have to configure the `sticky_cookie` values.
*   The `health_check` parameter within the `server` dictionary is no longer supported. Instead, manually set `max_fails` and `fail_timeout`.
-   [x] I have read the …
> Refactor HTTP Upstream module

- CHANGELOG.md
- defaults/main/template.yml
- molecule/default/converge.yml
- molecule/plus/converge.yml
- tasks/config/template-config.yml
- templates/http/default.conf.j2
- templates/http/proxy.j2
- templates/nginx.conf.j2
Refactor the `proxy` HTTP config template into its own separate file. All variables have changed (check [`defaults/main/template.yml`](https://github.com/nginxinc/ansible-role-nginx-config/blob/main/defaults/main/template.yml) for examples):
*   All `proxy_*` related variables now live under the `proxy` dictionary key, with the exception of `proxy_pass` and `proxy_cache_path`. You can specify the `proxy` dictionary key inside the `http`, `server`, and `location` contexts.
*   Remove the `nginx_config_main_template.http_settings.cache` dictionary variable. Use `nginx_config_http_template.*.proxy_cache_path` instead.
*   Remove the `location.websocket` variable. Use `location.proxy.set_header` instead:
```yaml
proxy:
set_header:
- field: Upgrade
value: $http_upgrade
- field: Connection …
```
> Refactor HTTP Proxy module

- templates/nginx.conf.j2
Describe the use case and detail of the change. If this PR addresses an issue on GitHub, make sure to include a link to that issue using one of the [supported keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) here in this description (not in the title of the PR).
Make the following `http_settings` options:
1. `access_log_format`
2. `keepalive_timeout`
So that I can configure the main template like this (to enable the HTTP directive):
```yaml
nginx_config_main_template_enable: true
nginx_config_main_template:
http_enable: true
http_settings:
gzip:
enable: true
```
-   [x] I have read the [CONTRIBUTING](https://github.com/nginxinc/ansible-role-nginx-config/bl …
> feat: make http settings access_log_format and keepalive_timeout optional

- CHANGELOG.md
- README.md
- meta/main.yml
- molecule/cleanup_module/molecule.yml
- molecule/common/requirements/plus_requirements.yml
- molecule/default/molecule.yml
- molecule/plus/molecule.yml
- molecule/plus/verify.yml
- molecule/stable_push/molecule.yml
Replace Molecule tests using Alpine 3.11 with Alpine 3.10 (to test NGINX App Protect configurations), Debian stretch with Debian buster (stretch has reached its EoL), and update list of supported platforms.
> Tweak Molecule tests to account for the current supported platforms

- CHANGELOG.md
- defaults/main/template.yml
- molecule/default/converge.yml
- molecule/plus/converge.yml
- templates/nginx.conf.j2
This commit adds two new directives for configuring in nginx.conf.
For completeness, the `server_names_hash_max_size` directive has been added here
as well.
Please see the documentation for these directives
[here](https://nginx.org/en/docs/http/ngx_http_core_module.html#server_names_hash_bucket_size).
Please let me know if there's anything that's missing/I still forgot! 🙏
Fixes https://github.com/nginxinc/ansible-role-nginx-config/issues/113
-   [x] I have checked that all Molecule tests pass …
> Add `server_names_hash_bucket_size` directive

- templates/http/proxy.j2
Make proxy_read_timeout a string instead of a boolean. Fixes #134.
> Make proxy_read_timeout a string instead of a boolean

- CHANGELOG.md
- defaults/main/template.yml
- molecule/default/converge.yml
- molecule/plus/converge.yml
- templates/http/auth.j2
- templates/http/default.conf.j2
Refactor the `auth` HTTP config template into its own separate file, as well as add support for `auth_jwt` directives. All variables have changed (check [`defaults/main/template.yml`](https://github.com/nginxinc/ansible-role-nginx-config/blob/main/defaults/main/template.yml) for examples):
*   All the various `auth` variables now live within their respective `auth` dictionaries.
*   `auth` configs are now supported within the `http`, `server`, and `location` contexts.
-   [x] I have checked that …
> Refactor HTTP auth modules

- CHANGELOG.md
- defaults/main/template.yml
- templates/http/app_protect.j2
- templates/nginx.conf.j2
Ensure the default values for the `nginx.conf` template match the default values found on a fresh NGINX installation. As well as fix an issue with the `app_protect.j2` template that was causing the default values for `nginx.conf` to fail. Fixes #147.
> Fix default template for nginx.conf

- CHANGELOG.md
- defaults/main/template.yml
- molecule/default/converge.yml
- molecule/plus/converge.yml
- templates/http/default.conf.j2
- templates/http/modules.j2
- templates/nginx.conf.j2
Refactor all modules used by the template so far with the exception of the `core` module. Check the CHANGELOG details for more information on what's changed exactly (the list of changes is to comprehensive for to include here).
> Refactor all minor modules

- CHANGELOG.md
- defaults/main/template.yml
- defaults/main/upload.yml
- molecule/default/converge.yml
- molecule/plus/converge.yml
- molecule/stable_push/converge.yml
- tasks/config/template-config.yml
- tasks/config/upload-config.yml
Add `backup` variable to template and upload parameters. Set to `false` if you don't want to keep backups of your previous NGINX config files. Closes #111.
> Make backup parameter optional

- CHANGELOG.md
- templates/http/default.conf.j2
this fixes the handling of single string based custom_directives in the http template.
without this, only a list of directives works because for single ones "custom_directive" is used inside a block that only works with "custom_directives" (with a plural s)
> HTTP template: Fix bug with single custom_directives

- CHANGELOG.md
- molecule/default/converge.yml
- molecule/default/verify.yml
- tasks/config/template-config.yml
Automatically create a NGINX `client_body_temp_path` directory if your NGINX config uses the directive. Closes #89.
> Automatically create NGINX client body temp path directory

- CHANGELOG.md
- molecule/common/requirements/oss_requirements.yml
- molecule/common/requirements/plus_requirements.yml
- molecule/default/converge.yml
- molecule/plus/converge.yml
- tasks/config/template-config.yml
- templates/stream/core.j2
- templates/stream/default.conf.j2
- templates/stream/modules.j2
- templates/stream/proxy.j2
- templates/stream/ssl.j2
- templates/stream/upstream.j2
Refactor NGINX `stream` templates. Follows in the footsteps of the NGINX `http` templates refactor.
> Refactor NGINX stream templates

- CHANGELOG.md
- defaults/main/template.yml
- templates/http/api.conf.j2
* Fix typo in the REST API template.
* Fix incorrect REST API and status log variable names in [`defaults/main/template.yml`](https://github.com/nginxinc/ansible-role-nginx-config/blob/main/defaults/main/template.yml).
* Fixes #208.
> Fix typo in REST API template

- CHANGELOG.md
- handlers/main.yml
Ansible check mode runs will no longer fail if NGINX has not yet been installed.
> Ansible check mode fails if NGINX is not installed

- .github/workflows/requirements/requirements_ansible.yml
- CHANGELOG.md
- meta/main.yml
- tasks/prerequisites/setup-selinux.yml
* Rename all modules to use the fully qualified collection name (FQCN) per Ansible guidelines.
* Bump the Ansible `community.general` collection to `4.6.1` and `community.docker` collection to `2.2.1`.
> Rename modules to use Ansible FQCNs

- CHANGELOG.md
- tasks/config/template-config.yml
Current tasks including loop, do not use labels. Thus, at the output we can see all the data of the loops items.
This little PR adds labels to tasks inside `template-config.yml`. 
Some label defaults have been taken from tasks content.
> Use labels for loops in template-config to reduce amount of data in output

- CHANGELOG.md
- defaults/main/template.yml
- molecule/default/converge.yml
- molecule/plus/converge.yml
- templates/http/default.conf.j2
- templates/http/modules.j2
Implement the `realip` module into the `http` core template. Closes #238.
> Implement RealIP module

- CHANGELOG.md
- defaults/main/template.yml
Improve the NGINX main config defaults to bring them closer to the standard NGINX defaults on a fresh NGINX install (part 2 after #252).
> Improve the NGINX main config defaults (2nd try)

- CHANGELOG.md
- README.md
- defaults/main/template.yml
- meta/main.yml
- molecule/plus/converge.yml
- templates/http/auth.j2
- templates/http/modules.j2
* `auth_jwt_require` now allows you to optionally set the `error` code you wish to return
* `health_check` now lets you set a `keepalive_time`.
> Support the latest NGINX Plus R26 directives

- .ansible-lint
- .github/workflows/requirements/requirements_ansible.yml
- CHANGELOG.md
- README.md
- molecule/plus/prepare.yml
- tasks/config/template-config.yml
- tasks/config/upload-config.yml
Bump the Ansible `community.general` collection to `5.5.0` and `community.docker` collection to `3.1.0`, and address Linter warnings.
> Bump Ansible collections

- CHANGELOG.md
- defaults/main/template.yml
- molecule/plus/converge.yml
- templates/http/app_protect.j2
Add support for the latest NGINX App Protect DoS directives (`app_protect_dos_arb_fqdn`, `app_protect_dos_api`, and `app_protect_dos_accelerated_mitigation`).
> Support the latest NGINX App Protect DoS directives

- .github/workflows/molecule.yml
- CHANGELOG.md
GitHub actions should now correctly skip *plus* scenarios only when the NGINX Plus license secrets are not present.
> Fix tests not running on external PRs

- tasks/config/template-config.yml
Fix the system user usage for checking the client body cache and proxy cache directories. When the structure of the `nginx_config_main_template` changed and the system user name was moved deeper into the structure, the two tasks to check the ownership of the client body cache and proxy cache did not get adjusted.
I am not proficient enough with molecule to add molecule tests for this, maybe someone can help with that?
> Fix system user usage in template-config

- CHANGELOG.md
- molecule/cleanup_module/molecule.yml
- molecule/default/molecule.yml
- molecule/plus/molecule.yml
- molecule/stable_push/molecule.yml
Explicitly specify `amd64` as the platform used in Molecule tests. This will ensure that tests work as expected when run on different host architectures (e.g. newer Macbooks with `arm` processors).
> Use `amd64` platform for Molecule tests

- .github/CODEOWNERS
- .github/workflows/galaxy.yml
- .github/workflows/molecule.yml
- .github/workflows/release-drafter.yml
- CHANGELOG.md
- meta/main.yml
ENHANCEMENTS:
Bump the minimum version of Ansible core required to run the role to `2.12` (`2.11` is no longer supported by Ansible).
BUG FIXES:
The `ignore-tags` GitHub actions key does not exist. Replace it with the correct key, `tags-ignore`.
> Replace non-existent GitHub actions key

- CHANGELOG.md
- molecule/common/requirements/oss_requirements.yml
- molecule/common/requirements/plus_requirements.yml
Update the versions of the Ansible NGINX and NGINX App Protect roles used by Molecule.
> Update NGINX role versions used by Molecule

- CHANGELOG.md
- defaults/main/template.yml
- molecule/default/converge.yml
- templates/http/core.j2
- templates/http/default.conf.j2
- templates/http/modules.j2
Removes long abandoned SPDY listening socket option.
Also moves http2 to a server level 
> Drop log unsupported "spdy", make "http2" a server level option.

- CHANGELOG.md
- tasks/config/upload-config.yml
Add handler to restart/reload nginx when SSL certs or keys change. Closes #318. When updating a SSL cert or keys, nginx needs to be reloaded before it will start serving the new cert. Otherwise the old (and potentially expired) cert will be used.
> Reload after ssl cert changed

- .github/workflows/requirements/requirements_ansible_lint.txt
- .github/workflows/requirements/requirements_molecule.txt
- CHANGELOG.md
> Uncomment the `ansible-compat` version from the CI/CD pipeline

- .github/workflows/f5-cla.yml
Adds a GitHub actions workflow configured for F5 contributor license agreement automation and compliance. This action is configured to target a shared signature store for F5 Open Source projects. As part of the configuration, the following GitHub usernames were whitelisted as maintainers:
* `oxpa`
* `alessfg`
Any contributors not included in this whitelist will be asked to review the [F5 CLA](https://github.com/f5/.github/blob/main/CLA/cla-markdown.md), upon a pull request, and post a comment agreeing to the terms before their contribution is merged.  
> ci: add gh action workflow for F5 CLA automation

- .github/workflows/ossf-scorecard.yml
- CHANGELOG.md
> ci: Implement OSSF Scorecard

- CHANGELOG.md
- tasks/config/template-config.yml
Fix the default path for the stream template deployment location.
> fix: Default path for stream template deployment location

- tasks/config/template-config.yml
#479 didn't quite fix the stream template path bug. Let's try again.
> fix: Create path for stream template deployment location

- CHANGELOG.md
- tasks/validate/validate.yml
```
TASK [nginx_config : Verify that you are using a supported Jinja2 version on your Ansible host] ********************************************************************************
fatal: [scar2 -> localhost]: FAILED! => {"msg": "Unexpected templating type error occurred on (Jinja2 {{ jinja2_version['stdout'] | regex_search('jinja version = ([\\\\d.]+)', '\\\\1') | first }} is supported.): 'NoneType' object is not iterable. 'NoneType' object is not iterable"}
```
Ansible check mode was failing to due the empty `jinja2_version` variable. Added `check_mode: false` to make it pass
> Check mode false

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/release-drafter.yml
- CHANGELOG.md
- README.md
See title. Not every mention has been changed since:
a) The Ansible project board still needs to be migrated
b) The roles are still under the nginxinc org in Ansible Galaxy
> chore: Replace nginxinc GH org mentions with nginx

- CHANGELOG.md
- defaults/main/template.yml
- molecule/common/files/nginx.conf
- molecule/complete/converge.yml
- molecule/complete_plus/converge.yml
- molecule/default/converge.yml
The default PID path has changed from `/var/run/nginx.pid` to `/run/nginx.pid` as of NGINX 1.27.5 and 1.28.0.
> fix: Default NGINX PID path

- handlers/main.yml
This is kinda required if `nginx_config` is used as standalone role to configure and enable the service after install.
> feat: Ensure NGINX service is enabled on boot when reloading

- CHANGELOG.md
- molecule/complete_plus/converge.yml
- templates/http/modules.j2
NGINX `set_real_ip_from` directive template parameter should be a list. Fixes #415.
> fix:  NGINX `set_real_ip_from` directive should be a list

- CHANGELOG.md
- tasks/validate/validate.yml
Disable `check_mode` for Ansible collections validation task.
> fix: Properly check Ansible collections in check mode

- CHANGELOG.md
- defaults/main/template.yml
- molecule/complete/converge.yml
- molecule/complete_plus/converge.yml
This is a simple fix that corrects the value of the default http_version to a string, which is what is required/expected by Nginx itself.
I'll admit to being lazy and not running any Molecule tests here, though one should probably be added to catch this. I have very little experience with Molecule, but I'm willing to add it if someone can give me a few hints on where to look and what to do.
> fix: Correct default `http_version` from float to string

- CHANGELOG.md
- defaults/main/template.yml
- molecule/complete/converge.yml
- molecule/complete_plus/converge.yml
- tasks/validate/validate.yml
- templates/http/modules.j2
- templates/stream/modules.j2
Add templating support for the `ngx_http_gzip_static_module` NGINX module. Closes #380.
> feat: Template support for the NGINX HTTP gzip static module

- .github/workflows/molecule.yml
- CHANGELOG.md
- defaults/main/template.yml
- molecule/entitlement_plus/converge.yml
- molecule/entitlement_plus/molecule.yml
- molecule/entitlement_plus/prepare.yml
- molecule/entitlement_plus/verify.yml
- templates/core.j2
- templates/nginx.conf.j2
Add templating support for the `ngx_mgmt_module` NGINX module.
> feat: Add support for the NGINX ngx_mgmt_module module.

- CHANGELOG.md
- defaults/main/template.yml
- molecule/complete/converge.yml
- molecule/complete_plus/converge.yml
- tasks/config/template-config.yml
The template backup parameter was made configurable in #205. For stream templates this was reverted in #217. With this patch the backup parameter for stream templates is configurable again. 
> fix: backup parameter of stream templates
